// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHDfj2WWHBHWPhNyVdqfu6dxgDjvhNMME',
    appId: '1:448213898855:web:2070ddd8a20606c988a6c2',
    messagingSenderId: '448213898855',
    projectId: 'fiducia-dc7e5',
    authDomain: 'fiducia-dc7e5.firebaseapp.com',
    storageBucket: 'fiducia-dc7e5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4WPEm6QfBY0cPvMkxZbEPeUvcck1v4vQ',
    appId: '1:448213898855:android:f5a0cc641016a89688a6c2',
    messagingSenderId: '448213898855',
    projectId: 'fiducia-dc7e5',
    storageBucket: 'fiducia-dc7e5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhbmqw1_B_FOZ-MZ8X2AsGrv0noPqQw5w',
    appId: '1:448213898855:ios:73e20fb8eba5b68888a6c2',
    messagingSenderId: '448213898855',
    projectId: 'fiducia-dc7e5',
    storageBucket: 'fiducia-dc7e5.firebasestorage.app',
    iosBundleId: 'com.example.appFinancas',
  );
}
